"""phase3_tax_audit_tables

Revision ID: e1bd50048ee7
Revises: b6a1bd4db2c6
Create Date: 2026-06-15 06:30:45.079679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1bd50048ee7'
down_revision: Union[str, None] = 'b6a1bd4db2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_3cd_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('clause_number', sa.String(length=10), nullable=True),
    sa.Column('clause_text', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('ai_suggested_response', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_applicable', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gst_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('return_type', sa.String(length=20), nullable=False),
    sa.Column('filing_period', sa.String(length=10), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_taxable_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_igst', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_cgst', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_sgst', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('upload_status', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itc_mismatches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('filing_period', sa.String(length=10), nullable=True),
    sa.Column('itc_in_2b', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('itc_in_3b', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('mismatch_type', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tds_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('deductor_name', sa.String(length=255), nullable=True),
    sa.Column('deductor_tan', sa.String(length=15), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('tds_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('tds_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('matched_in_books', sa.Boolean(), nullable=True),
    sa.Column('book_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tds_records')
    op.drop_table('itc_mismatches')
    op.drop_table('gst_returns')
    op.drop_table('form_3cd_responses')
    # ### end Alembic commands ###
