"""month5_updates

Revision ID: 3722a1080517
Revises: f2146773c95f
Create Date: 2026-06-10 15:32:50.810666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3722a1080517'
down_revision: Union[str, None] = 'f2146773c95f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=True),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('realm_id', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_findings_engagement', 'findings', ['engagement_id'], unique=False)
    op.create_index('idx_findings_status', 'findings', ['status'], unique=False)
    op.create_index('idx_fraud_alerts_engagement', 'fraud_alerts', ['engagement_id'], unique=False)
    op.create_index('idx_fraud_alerts_status', 'fraud_alerts', ['status'], unique=False)
    op.create_index('idx_transactions_date', 'transactions', ['transaction_date'], unique=False)
    op.create_index('idx_transactions_engagement', 'transactions', ['engagement_id'], unique=False)
    op.create_index('idx_transactions_flagged', 'transactions', ['is_flagged'], unique=False)
    op.create_index('idx_transactions_risk_score', 'transactions', ['risk_score'], unique=False)
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.add_column('findings', sa.Column('jira_issue_key', sa.String(length=255), nullable=True))
    op.add_column('findings', sa.Column('jira_issue_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'jira_issue_url')
    op.drop_column('findings', 'jira_issue_key')
    op.drop_column('users', 'onboarding_completed')
    op.drop_index('idx_transactions_risk_score', table_name='transactions')
    op.drop_index('idx_transactions_flagged', table_name='transactions')
    op.drop_index('idx_transactions_engagement', table_name='transactions')
    op.drop_index('idx_transactions_date', table_name='transactions')
    op.drop_index('idx_fraud_alerts_status', table_name='fraud_alerts')
    op.drop_index('idx_fraud_alerts_engagement', table_name='fraud_alerts')
    op.drop_index('idx_findings_status', table_name='findings')
    op.drop_index('idx_findings_engagement', table_name='findings')
    op.drop_table('connector_tokens')
    # ### end Alembic commands ###
