"""phase3_modules_superadmin

Revision ID: b6a1bd4db2c6
Revises: 00e8a20d9fe2
Create Date: 2026-06-15 05:54:03.805443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6a1bd4db2c6'
down_revision: Union[str, None] = '00e8a20d9fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('modules', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # Give all existing orgs the default modules
    op.execute("""
        UPDATE organizations
        SET modules = '["financial_audit", "internal_audit"]'::jsonb
        WHERE modules IS NULL
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superadmin')
    op.drop_column('organizations', 'modules')
    # ### end Alembic commands ###
